language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

before_script: composer install --dev

script:
    -phpunit --verbose --coverage-text
    -vendor/fabpot/php-cs-fixer/php-cs-fixer fix ./src --dry-run --level="all" -vv